const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function generateImage(prompt) {
  const model = genAI.getGenerativeModel({
    model: "gemini-2.5-flash-image",
  });

  const result = await model.generateContent(prompt);

  const imagePart = result.response.candidates[0].content.parts.find(
    (p) => p.inlineData
  );

  if (!imagePart) {
    throw new Error("No image generated by Gemini");
  }

  return imagePart.inlineData.data; // base64
}

module.exports = generateImage;
